// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int>("EapVolume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eap_volume");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_en");

                    b.Property<string>("EtName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_et");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER")
                        .HasColumnName("language");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("manager_name");

                    b.Property<int>("StudyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("study_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("curriculums", (string)null);
                });

            modelBuilder.Entity("Domain.CurriculumSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("TEXT")
                        .HasColumnName("curriculum_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SubjectId");

                    b.ToTable("curriculum_subjects", (string)null);
                });

            modelBuilder.Entity("Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AssessmentForm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assessment_form");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int>("EapVolume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eap_volume");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_en");

                    b.Property<string>("EtName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_et");

                    b.Property<string>("TeacherName")
                        .HasColumnType("TEXT")
                        .HasColumnName("teacher_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Domain.CurriculumSubject", b =>
                {
                    b.HasOne("Domain.Curriculum", null)
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
